FROM golang:latest AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY . /src/

WORKDIR /src/walletshield

ENV GONOSUMCHECK=*
ENV GONOSUMDB=*
ENV GOFLAGS=-mod=mod

RUN go mod tidy 2>&1 && \
    go build -trimpath -ldflags="-buildid=" -o /walletshield . 2>&1

FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && addgroup --system --gid 1001 app \
    && adduser --system --uid 1001 --ingroup app --no-create-home app

COPY --from=builder /walletshield /usr/local/bin/walletshield

USER app

ENTRYPOINT ["/usr/local/bin/walletshield"]
CMD ["-h"]
